### ISSUE TITLE
There may be some bugs in the ranking order of the point cloud registration leaderboard?

### ISSUE THREAD

**Issue by MaxChanger** [paul007pl/MVP_Benchmark#10]
I don't know if it is correct, I think there may be some bugs in the ranking order of the point cloud registration leaderboard?
It looks like it’s currently sorted by submission time, not by some kind of metric.

**Comment by MaxChanger** [comment]
![image](https://user-images.githubusercontent.com/35401968/128877683-4b2874c3-1004-4079-bd98-fd00f5a6049d.png)

**Comment by wutong16** [comment]
Hi! Sorry for the confusion. 
The completion and registration challenges share the same set of metrics and the highest priority is assigned to **CD_Loss@Com**, which is not friendly to the registration trend. We'll try to fix the problem.
Currently, we can get the correct ranking by clicking the title of the last column, i.e., **MSE@Reg**.
