### ISSUE TITLE
How to register as a team?

### ISSUE THREAD

**Issue by shenqildr** [paul007pl/MVP_Benchmark#2]
Hello,
I tried to register and participate but I did not find the option for registration as a team? How many members can be contained in a team?

**Comment by wutong16** [comment]
Hi @shenqildr,

First, you'll need to create an account on the [Codalab platform](https://competitions.codalab.org/) and then log in as below:
![image](https://user-images.githubusercontent.com/28827385/125555684-852d571b-29af-46ea-bca4-80e5c6dc434d.png)

Then you could easily register and participate in [our competition](https://competitions.codalab.org/competitions/33430) as below:
![image](https://user-images.githubusercontent.com/28827385/125555225-15df772b-1713-4385-a8ef-eb518fa05a3f.png)

The number of team members is not limited and one team only needs one account to submit the results.

Good luck to you and your team!

**Comment by shenqildr** [comment]
Thanks for your quick reply!
