### ISSUE TITLE
whether to allow the use of traditional methods?

### ISSUE THREAD

**Issue by wanghuayou1028** [paul007pl/MVP_Benchmark#5]
For the registration task, whether to allow the use of traditional methods?

**Comment by paul007pl** [comment]
It is allowed to use traditional methods, but it is not encouraged.
It is also not encouraged to refine your registration results by using ICP...
In the phase II, we will test your submmited methods, and we won't use ICP-based refinements.

1. it can be unfair
2. many traditional methods are memory-expensive and time-consuming
3. the objective of this challenge is "learn to register partial point clouds"

In the end, we prefer to select the learning-based methods as the best solutions, unless significant improvements and clear contributions are achieved in the proposed traditional methods.
