### ISSUE TITLE
Missing super resolution dataset

### ISSUE THREAD

**Issue by rspezialetti** [paul007pl/MVP_Benchmark#6]
Hi,

thanks for releasing the code and dataset. However, on the paper you provide results at different resolutions (2.048 - 4.096 - 8.192 16.384), which are not present in the current released dataset. Why have they been removed ?

Thanks
Riccardo

**Comment by paul007pl** [comment]
Hi Riccardo,

Thanks for asking.
This repo is for our iccv2021 workshop, the mvp challenges.
In this challenge, we will evaluate 2 tasks, completion and registration for 2048 points.
It starts recently, and you are welcome to participate.

As for super-resolution datasets, you can find in my repo, VRCNet
https://paul007pl.github.io/projects/VRCNet.html

Best,
Liang

**Comment by rspezialetti** [comment]
Hi Liang,

thanks, i will close this issue.!

Best,
Riccardo
