### ISSUE TITLE
I may be stupid but where can I find the best_cd_t_network.pth

### ISSUE THREAD

**Issue by xkevas24** [paul007pl/MVP_Benchmark#7]
After reading your paper about VRCNet, I found this net is based on a prior pth. But I cannot find best_cd_t_network.pth in this repo. I found pretrained_vrcnet_2048.pth in VRCNet repo, but it seemed not working... help me...

**Comment by paul007pl** [comment]
Hi, I am sure you are not stupid, and I am sorry to make this repo misleading.  
This net is not based on a prior pth.
If you are training the model (from scratch), you can set the pth to be null.
After training, you can set the pth to your pretrained model and then test the model.
You can find my pretrained model in another repo "VRCNet".  
Good luck~

**Comment by xkevas24** [comment]
Thank you for your reply! Finally, I am successfully running your demo. I installed your env for about a week. I am crying... I hope I can know your network well and get a good result in your online challenge!

**Comment by paul007pl** [comment]
You finally resolve all issues. Congrats!
Wish you good luck~

**Comment by xkevas24** [comment]
The last question is how to convert to a CAD file?
